import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Banner from '../components/Banner/Banner';
import ShopContainer from '../components/ShopContainer/ShopContainer';
import dummyData from '../public/dummyData';
import fetchData from '../public/fetchData/fetchData';
import { useContext } from 'react';
import { StoresContext } from '../public/Context/StoreContext';
export async function getStaticProps(context) {
	// console.log('DUMMY DATA', dummyData);

	const coffeeShops = await fetchData(
		'96.093292',
		'21.954510',
		'coffee shops',
		10
	);
	// console.log('COFFEESHOPS >>', coffeeShops);
	return {
		props: {
			coffeeShops,
		},
	};
}

export default function Home({ coffeeShops }) {
	// console.log('PROPS >>', props);
	const { state } = useContext(StoresContext);
	return (
		<>
			<Head>
				<title>Discover Coffee Stores</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Banner />
			{state.nearCoffeeShops.length > 0 && (
				<ShopContainer data={state.nearCoffeeShops} title="Nearby Cafe`" />
			)}
			<ShopContainer data={coffeeShops} title="Mandalay Cafe`" />
		</>
	);
}
